services:
  viatim:
    container_name: viatim-backend
    platform: linux/amd64
    image: viatim-main
    build:
      context: .
      target: development
    volumes:
      - .:/app
      - /app/dist
      - /app/node_modules
    ports:
      - "3001:3000"
    command: npm run start:dev
    env_file:
      - .env.dev
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: viatim
      POSTGRES_PASSWORD: viatim
      POSTGRES_DB: viatim
